spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db?verifyServerCertificate=false&useSSL=false&requireSSL=false"
    username: "user"
    password:  "user"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      cache:
        use_second_level_cache: false
      region:
        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

    show-sql: true
  application:
    name: ActivityTrackerServer
server:
  port: 8081
